---
- name: Copying Files from controller to hosts
  hosts: planetexpress
  connection: ssh
  gather_facts: true

  tasks: 

   - name: Copy Fry's resume to hosts
     ansible.builtin.copy:
        src: ~/mycode/files/fry.txt   # on the controller
        dest: ~/fry.txt  #home directory on hosts
